const products = [
    {
        '_id': '1',
        'name': 'iphone XR',
        'image': '/resources/images/products/phones/iphone xr blue.jpg',
        'description' : '4GB RAM, 256GB Internal storage, ',
        'brand' : 'Apple',
        'category' : 'Phones',
        'price' : 600000,
        'countInStock' : 10,
        'rating' : 4.5, 
        'numReviews' : 12,
    },
    {
        '_id': '2',
        'name': 'Nokia X6',
        'image': '/resources/images/products/phones/nokia 1.jpg',
        'description' : '4GB RAM, 64GB Internal storage, ',
        'brand' : 'Nokia',
        'category' : 'Phones',
        'price' : 60000,
        'countInStock' : 10,
        'rating' : 4.5, 
        'numReviews' : 12,
    },
    {
        '_id': '3',
        'name': 'iphone 12 pro max',
        'image': '/resources/images/products/phones/iphone-12-pro-max-silver.jpg',
        'description' : '6GB RAM, 256GB Internal storage, ',
        'brand' : 'Apple',
        'category' : 'Phones',
        'price' : 600000,
        'countInStock' : 0,
        'rating' : 4.5, 
        'numReviews' : 12,
    },
    {
        '_id': '4',
        'name': 'Xiaomi Redmi 1',
        'image': '/resources/images/products/phones/redmi 1.jpg',
        'description' : '2GB RAM, 32GB Internal storage, ',
        'brand' : 'Xiaomi',
        'category' : 'Phones',
        'price' : 45000,
        'countInStock' : 10,
        'rating' : 4.5, 
        'numReviews' : 12,
    },
    {
        '_id': '5',
        'name': 'Samsung Galaxy S21 ultra',
        'image': '/resources/images/products/phones/samsung s21 ultra.jpg',
        'description' : '4GB RAM, 256GB Internal storage, ',
        'brand' : 'Samsung',
        'category' : 'Phones',
        'price' : 650000,
        'countInStock' : 10,
        'rating' : 4.5, 
        'numReviews' : 12,
    },
    {
        '_id': '6',
        'name': 'Vivo Y19',
        'image': '/resources/images/products/phones/vivo y19.jpg',
        'description' : '4GB RAM, 128GB Internal storage, ',
        'brand' : 'Vivo',
        'category' : 'Phones',
        'price' : 70000,
        'countInStock' : 50,
        'rating' : 4.5, 
        'numReviews' : 12,
    },
    {
        '_id': '7',
        'name': 'Tecno Phantom X',
        'image': '/resources/images/products/phones/tecno phantom x.jpg',
        'description' : '6GB RAM, 128GB Internal storage, Android 11 HiOS 13 ',
        'brand' : 'Tecno',
        'category' : 'Phones',
        'price' : 100000,
        'countInStock' : 5,
        'rating' : 4.3, 
        'numReviews' : 12,
    },
    {
        '_id': '8',
        'name': 'Infinix Zero X',
        'image': '/resources/images/products/phones/infinix zero x.jpg',
        'description' : '4GB RAM, 128GB Internal storage, ',
        'brand' : 'Infinix',
        'category' : 'Phones',
        'price' : 80000,
        'countInStock' : 50,
        'rating' : 4.5, 
        'numReviews' : 12,
    },
    
]

export default products